cluster:
  name: odyssey
  profile: lsf3
  cores: 4
  timeout: 10000
  delay: 10

dir:
  results: results/d1
  doc: doc
  ref: ref
  data: data
  log: log

pipeline:
  timestamp: True

input_dir: data/d1

log_dir: log


gtf: /n/hsphS10/hsphfs1/chb/biodata/genomes/danio_rerio/zv9/ref/Danio_rerio.Zv9.68.gtf
ref: /n/hsphS10/hsphfs1/chb/biodata/genomes/danio_rerio/zv9/bowtie/zebrafish_ensembl
ref_fasta: /n/hsphS10/hsphfs1/chb/biodata/genomes/danio_rerio/zv9/seq/Danio_rerio.Zv9.68.dna.toplevel.fa

annotation:
  name: zebrafish
  genome: danRer7
  file: /n/hsphS10/hsphfs1/chb/biodata/genomes/danio_rerio/zv9/ref/Danio_rerio.Zv9.68.gtf

program:
  fastqc: fastqc
  tophat: tophat
  bowtie: bowtie
  picard: /n/home05/kirchner/opt/lib/java/picard-tools-1.74

stage:
  fastqc:
    name: fastqc
    program: fastqc
    options:
      - [--noextract]

  cutadapt:
    name: cutadapt
    program: cutadapt
    platform: [illumina, polya]
    options:
      - [--error-rate, 0.1]
      - [--minimum-length, 20]

  tophat:
    name: tophat
    program: tophat
    quality_format: sanger
    max_errors: 2

  htseq-count:
    name: htseq-count
    program: htseq-count
    options:
      - [--stranded=no]
      - [--type=exon]
      - [--idattr=gene_id]
      - [--mode=union]

  deseq:
    comparisons:
      - [wttu, tplusn]
      - [wttu, tonly]
      - [wttu, nonly]

  rseqc:
    name: rseqc

  rna-seqc:
    program: /n/HSPH/local/share/java

  coverage:
    name: coverage
    program: picard
    ref:
      name: zebrafish
      file: /n/home05/kirchner/hsph/biodata/genomes/danio_rerio/zv9/ref/Danio_rerio.Zv9.68.refflat
    ribo: /n/home05/kirchner/hsph/biodata/genomes/danio_rerio/zv9/ref/Danio_rerio.Zv9.68.rrna.bed


run:
  [fastqc, cutadapt, fastqc, tophat, rseqc, coverage, htseq-count, deseq]
