cluster:
  name: odyssey
  profile: lsf
  cores: 4
  timeout: 10000
  delay: 10

dir:
  results: results/test
  doc: doc
  ref: ref
  data: data

log_dir: log

gtf: ref/genes.gtf
ref: /n/scratch00/hsph/biodata/genomes/Mmusculus/mm9/bowtie/mm9
ref_fasta: /n/scratch00/hsph/biodata/genomes/Mmusculus/mm9/bowtie/mm9.fa

annotation:
  name: mm9
  file: ref/genes.gtf

input:
  data/Sample_SC34.R1.fastq:
    condition: ESC_WT
  data/Sample_SC35.R1.fastq:
    condition: ESC_KO
  data/Sample_SC36.R1.fastq:
    condition: NSC_WT
  data/Sample_SC37.R1.fastq:
    condition: NSC_KO

program:
  fastqc: fastqc
  tophat: tophat
  bowtie: bowtie
  picard: /n/HSPH/local/share/java/picard

stage:
  fastqc:
    name: fastqc
    program: fastqc
    options:
      - [--noextract]

  cutadapt:
    program: cutadapt
    platform: [illumina, polya]
    options:
      - [--error-rate, 0.1]
      - [--minimum-length, 20]
      - [--quality-cutoff, 20]

  tophat:
    name: tophat
    program: tophat
    quality_format: sanger
    max_errors: 2

  rna_seqc:
    name: rna_seqc
    program: /n/HSPH/local/share/java/RNA-SeQC/RNA-SeQC_v1.1.7.jar
    options:
      - [-singleEnd]

  htseq-count:
    name: htseq-count
    program: htseq-count
    options:
      - [--stranded=no]
      - [--type=exon]
      - [--idattr=gene_id]
      - [--mode=union]

  deseq:
    name: deseq
    tests:
      - [ESC_WT, ESC_KO]
      - [NSC_WT, NSC_KO]

  rseqc:
    name: rseqc

  coverage:
    name: coverage
    program: picard
    ref:
      name: mm9
      file: ref/mouse_refflat.txt
    ribo: ref/mouse_rrna_final.bed

run:
  [fastqc, cutadapt, tophat, rseqc, coverage, htseq-count, deseq]
