details:
- algorithm:
    adapters:
    - truseq
    - polya
    aligner: star
    quality_format: Standard
    strandedness: unstranded
    trim_reads: false
  analysis: RNA-seq
  description: RE1_1
  files:
  - /n/data1/cores/bcbio/gu_rnaseq/data/fastq/160107Gu_D16-295_NA_sequence.fastq
  genome_build: mm10
  metadata:
    batch: 1
    day: 1
    fastqcode: D16-295
    sampletype: retinal
- algorithm:
    adapters:
    - truseq
    - polya
    aligner: star
    quality_format: Standard
    strandedness: unstranded
    trim_reads: false
  analysis: RNA-seq
  description: RE2_1
  files:
  - /n/data1/cores/bcbio/gu_rnaseq/data/fastq/160107Gu_D16-296_NA_sequence.fastq
  genome_build: mm10
  metadata:
    batch: 1
    day: 2
    fastqcode: D16-296
    sampletype: retinal
- algorithm:
    adapters:
    - truseq
    - polya
    aligner: star
    quality_format: Standard
    strandedness: unstranded
    trim_reads: false
  analysis: RNA-seq
  description: RE3_1
  files:
  - /n/data1/cores/bcbio/gu_rnaseq/data/fastq/160107Gu_D16-297_NA_sequence.fastq
  genome_build: mm10
  metadata:
    batch: 1
    day: 3
    fastqcode: D16-297
    sampletype: retinal
- algorithm:
    adapters:
    - truseq
    - polya
    aligner: star
    quality_format: Standard
    strandedness: unstranded
    trim_reads: false
  analysis: RNA-seq
  description: RE4_1
  files:
  - /n/data1/cores/bcbio/gu_rnaseq/data/fastq/160107Gu_D16-298_NA_sequence.fastq
  genome_build: mm10
  metadata:
    batch: 1
    day: 4
    fastqcode: D16-298
    sampletype: retinal
- algorithm:
    adapters:
    - truseq
    - polya
    aligner: star
    quality_format: Standard
    strandedness: unstranded
    trim_reads: false
  analysis: RNA-seq
  description: RE5_1
  files:
  - /n/data1/cores/bcbio/gu_rnaseq/data/fastq/160107Gu_D16-299_NA_sequence.fastq
  genome_build: mm10
  metadata:
    batch: 1
    day: 5
    fastqcode: D16-299
    sampletype: retinal
- algorithm:
    adapters:
    - truseq
    - polya
    aligner: star
    quality_format: Standard
    strandedness: unstranded
    trim_reads: false
  analysis: RNA-seq
  description: LE1_1
  files:
  - /n/data1/cores/bcbio/gu_rnaseq/data/fastq/160107Gu_D16-300_NA_sequence.fastq
  genome_build: mm10
  metadata:
    batch: 1
    day: 1
    fastqcode: D16-300
    sampletype: lung
- algorithm:
    adapters:
    - truseq
    - polya
    aligner: star
    quality_format: Standard
    strandedness: unstranded
    trim_reads: false
  analysis: RNA-seq
  description: LE2_1
  files:
  - /n/data1/cores/bcbio/gu_rnaseq/data/fastq/160107Gu_D16-301_NA_sequence.fastq
  genome_build: mm10
  metadata:
    batch: 1
    day: 2
    fastqcode: D16-301
    sampletype: lung
- algorithm:
    adapters:
    - truseq
    - polya
    aligner: star
    quality_format: Standard
    strandedness: unstranded
    trim_reads: false
  analysis: RNA-seq
  description: LE3_1
  files:
  - /n/data1/cores/bcbio/gu_rnaseq/data/fastq/160107Gu_D16-302_NA_sequence.fastq
  genome_build: mm10
  metadata:
    batch: 1
    day: 3
    fastqcode: D16-302
    sampletype: lung
- algorithm:
    adapters:
    - truseq
    - polya
    aligner: star
    quality_format: Standard
    strandedness: unstranded
    trim_reads: false
  analysis: RNA-seq
  description: LE4_1
  files:
  - /n/data1/cores/bcbio/gu_rnaseq/data/fastq/160107Gu_D16-303_NA_sequence.fastq
  genome_build: mm10
  metadata:
    batch: 1
    day: 4
    fastqcode: D16-303
    sampletype: lung
- algorithm:
    adapters:
    - truseq
    - polya
    aligner: star
    quality_format: Standard
    strandedness: unstranded
    trim_reads: false
  analysis: RNA-seq
  description: LE5_1
  files:
  - /n/data1/cores/bcbio/gu_rnaseq/data/fastq/160107Gu_D16-304_NA_sequence.fastq
  genome_build: mm10
  metadata:
    batch: 1
    day: 5
    fastqcode: D16-304
    sampletype: lung
- algorithm:
    adapters:
    - truseq
    - polya
    aligner: star
    quality_format: Standard
    strandedness: unstranded
    trim_reads: false
  analysis: RNA-seq
  description: LE1_2
  files:
  - /n/data1/cores/bcbio/gu_rnaseq/data/fastq/160107Gu_D16-3958_NA_sequence.fastq
  genome_build: mm10
  metadata:
    batch: 2
    day: 1
    fastqcode: D16-3958
    sampletype: lung
- algorithm:
    adapters:
    - truseq
    - polya
    aligner: star
    quality_format: Standard
    strandedness: unstranded
    trim_reads: false
  analysis: RNA-seq
  description: LE2_2
  files:
  - /n/data1/cores/bcbio/gu_rnaseq/data/fastq/160107Gu_D16-3959_NA_sequence.fastq
  genome_build: mm10
  metadata:
    batch: 2
    day: 2
    fastqcode: D16-3959
    sampletype: lung
- algorithm:
    adapters:
    - truseq
    - polya
    aligner: star
    quality_format: Standard
    strandedness: unstranded
    trim_reads: false
  analysis: RNA-seq
  description: LE3_2
  files:
  - /n/data1/cores/bcbio/gu_rnaseq/data/fastq/160107Gu_D16-3960_NA_sequence.fastq
  genome_build: mm10
  metadata:
    batch: 2
    day: 3
    fastqcode: D16-3960
    sampletype: lung
- algorithm:
    adapters:
    - truseq
    - polya
    aligner: star
    quality_format: Standard
    strandedness: unstranded
    trim_reads: false
  analysis: RNA-seq
  description: LE4_2
  files:
  - /n/data1/cores/bcbio/gu_rnaseq/data/fastq/160107Gu_D16-3961_NA_sequence.fastq
  genome_build: mm10
  metadata:
    batch: 2
    day: 4
    fastqcode: D16-3961
    sampletype: lung
- algorithm:
    adapters:
    - truseq
    - polya
    aligner: star
    quality_format: Standard
    strandedness: unstranded
    trim_reads: false
  analysis: RNA-seq
  description: LE5_2
  files:
  - /n/data1/cores/bcbio/gu_rnaseq/data/fastq/160107Gu_D16-3962_NA_sequence.fastq
  genome_build: mm10
  metadata:
    batch: 2
    day: 5
    fastqcode: D16-3962
    sampletype: lung
fc_date: '2016-06-15'
fc_name: project
upload:
  dir: ../final
